blank_issues_enabled: false
contact_links:
  - name: 💬 General Questions
    url: https://github.com/daxlib/dev-daxlib-svg/discussions
    about: Please ask and answer questions as a discussion thread